# Generated by Django 4.2.7 on 2023-11-22 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productbrand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductBrand',
        ),
    ]
