# Generated by Django 4.2.7 on 2023-11-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_type', models.CharField(blank=True, choices=[('color', 'color'), ('size', 'size')], max_length=100, null=True)),
            ],
        ),
    ]
