# Generated by Django 4.2.7 on 2023-11-23 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
