# Generated by Django 5.0 on 2023-12-07 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'productgallery', 'verbose_name_plural': 'product gallery'},
        ),
    ]
