# Generated by Django 4.2.7 on 2023-11-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='variation_type',
            field=models.CharField(blank=True, choices=[('color', 'color'), ('size', 'size')], max_length=100, null=True),
        ),
    ]
