# Generated by Django 4.2.7 on 2023-11-23 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_variation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='variation_type',
        ),
    ]
